apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cicd
  name: cicd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cicd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cicd
    spec:
      containers:
      - image: pan0922/flask-study:latest
        name: cicd
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: cicd
